export const CREATE_POST_ACTION_TYPE = 'CREATE_POST';
export const DELETE_POST_ACTION_TYPE = 'DELETE_POST';
export const EDIT_POST_ACTION_TYPE = 'EDIT_POST';
export const UPVOTE_POST_ACTION_TYPE = 'UPVOTE_POST';
export const ADD_COMMENT_ACTION_TYPE = 'ADD_COMMENT';
export const DELETE_COMMENT_ACTION_TYPE = 'DELETE_COMMENT';
