export const REQUEST_ALL_POSTS_ACTION_TYPE = 'REQUEST_ALL_POSTS';
export const RECEIVE_ALL_POSTS_ACTION_TYPE = 'RECEIVE_ALL_POSTS';
export const CREATE_POST_ACTION_TYPE = 'CREATE_POST';
export const EDIT_POST_ACTION_TYPE = 'EDIT_POST';
export const DELETE_POST_ACTION_TYPE = 'DELETE_POST';
export const UPVOTE_POST_ACTION_TYPE = 'UPVOTE_POST';
export const DOWNVOTE_POST_ACTION_TYPE = 'DOWNVOTE_POST';
export const REQUEST_COMMENTS_FOR_POST_ACTION_TYPE =
	'REQUEST_COMMENTS_FOR_POST';
export const RECEIVE_COMMENTS_FOR_POST_ACTION_TYPE =
	'RECEIVE_COMMENTS_FOR_POST';
export const ADD_COMMENT_ACTION_TYPE = 'ADD_COMMENT';
export const EDIT_COMMENT_ACTION_TYPE = 'EDIT_COMMENT';
export const DELETE_COMMENT_ACTION_TYPE = 'DELETE_COMMENT';
export const UPVOTE_COMMENT_ACTION_TYPE = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT_ACTION_TYPE = 'DOWNVOTE_COMMENT';
export const REQUEST_ALL_CATEGORIES_ACTION_TYPE = 'REQUEST_ALL_CATEGORIES';
